import type { Metadata } from 'next';
import './globals.css';
import { Rubik } from 'next/font/google';

/**
 * We need to add this line so NextJs doesn't try to build static pages.
 * We can't use static pages because we use cookies
 */
export const dynamic = 'force-dynamic';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
