import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import Footer from './(dashboard)/components/content/footer/Footer';

import './globals.css';

/**
 * We need to add this line so NextJs doesn't try to build static pages.
 * We can't use static pages because we use cookies
 */
export const dynamic = 'force-dynamic';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className='min-h-screen'>
      <body className={`${rubik.className}`}>{children}</body>
    </html>
  );
}
