import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';

import './globals.css';

/**
 * We need to add this line so NextJs doesn't try to build static pages.
 * We can't use static pages because we use cookies
 */
export const dynamic = 'force-dynamic';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${rubik.className} md:h-screen md:grid md:grid-cols-[11rem_1fr] md:grid-rows-[auto_1fr_auto_auto] bg-gradient-to-b from-primary to-white bg-no-repeat`}>{children}</body>
    </html>
  );
}
