import { notFound } from "next/navigation";
import { createClient } from "utils/supabase/server";
import DeleteTicketButton from "./DeleteTicketButton";

/**
 * If this value is set to 'false', it will render a 404 page for pages that haven't been pre-rendered
 * Leaving this as 'True' is the default and it will try to fetch the data and create the page at runtime
 */
export const dynamicParams = true;

export async function generateMetadata({ params }) {
  const supabase = createClient();
  const { data: ticket, error } = await supabase
    .from("Tickets")
    .select()
    .eq("id", params.id)
    .single();

  return {
    title: `Helpdesk | ${ticket?.title || "Ticket not found"}`,
    description: "Generated by create next app",
  };
}

export async function getTicket(id) {
  const supabase = createClient();
  const { data: ticket } = await supabase
    .from("Tickets")
    .select()
    .eq("id", id)
    .single();

  if (!ticket) {
    notFound();
  }

  return ticket;
}

export default async function TicketDetails({ params }) {
  const ticket = await getTicket(params.id);

  const supabase = createClient();
  const { data } = await supabase.auth.getSession();

  return (
    <main>
      <nav>
        <h2>Ticket Details</h2>
        <div className="ml-auto">
          {data.session.user.email === ticket.user_email ? (
            <DeleteTicketButton id={ticket.id} />
          ) : null}
        </div>
      </nav>
      <div className="card">
        <h3>{ticket.title}</h3>
        <p>{ticket.body}</p>
        <small>Created by {ticket.user_email}</small>
        <p>{ticket.body}</p>
        <div className={`pill ${ticket.priority}`}>
          {ticket.priority} priority
        </div>
      </div>
    </main>
  );
}
